import os

nomes_certos = {
    'estados_unidos': 'Estados Unidos',
    'alemanha': 'Alemanha',
    'australia': 'Austrália',
    'china': 'China',
    'reino_unido': 'Reino Unido',
    'india': 'Índia',
    'brasil': 'Brasil',
    'franca': 'França',
    'mexico': 'México',
    'espanha': 'Espanha',
    'canada': 'Canadá',
    'russia': 'Rússia',
    'japao': 'Japão',
    'turquia': 'Turquia',
    'italia': 'Itália',
    'argentina': 'Argentina', 
    'chile': 'Chile',
    'africa_do_sul': 'África do Sul',
    'suica': 'Suíça',
    'egito': 'Egito ',
    'coreia_do_sul': 'Coreia do Sul',
    'grecia': 'Grécia',
    'argelia': 'Argélia',
    'polonia': 'Polônia',
    'ucrania': 'Ucrânia',
    'austria': 'Áustria',
    'peru': 'Peru',
    'dinamarca': 'Dinamarca',
    'arabia_saudita': 'Arábia Saudita',
    'suecia': 'Suécia',
    'gana': 'Gana',
    'iraque': 'Iraque',
    'paises_baixos': 'Países Baixos',
    'jamaica': 'Jamaica',
    'nigeria': 'Nigéria',
    'cuba': 'Cuba',
    'belgica': 'Bélgica',
    'nova_zelandia': 'Nova Zelândia',
    'uruguai': 'Uruguai',
    'portugal': 'Portugal',
    'irlanda': 'Irlanda',
    'noruega': 'Noruega',
    'israel': 'Israel',
    'azerbaijao': 'Azerbaijão',
    'tailandia': 'Tailândia',
    'bangladesh': 'Bangladesh',
    'croacia': 'Croácia',
    'senegal': 'Senegal',
    'republica_tcheca': 'República Tcheca',
    'indonesia': 'Indonésia',
    'vietna': 'Vietnã',
    'malasia': 'Malásia',
    'finlandia': 'Finlândia',
    'ira': 'Irã',
    'quenia': 'Quênia',
    'paquistao': 'Paquistão',
    'colombia': 'Colômbia',
    'hungria': 'Hungria',
    'marrocos': 'Marrocos',
    'romenia': 'Romênia',
    'tunisia': 'Tunísia',
    'servia': 'Sérvia',
    'angola': 'Angola',
    'bolivia': 'Bolívia',
    'singapura': 'Singapura',
    'siria': 'Síria',
    'bielorrussia': 'Bielorrússia',
    'uganda': 'Uganda',
    'equador': 'Equador',
    'filipinas': 'Filipinas',
    'etiopia': 'Etiópia',
    'afeganistao': 'Afeganistão',
    'camaroes': 'Camarões',
    'uzbequistao': 'Uzbequistão',
    'venezuela': 'Venezuela',
    'madagascar': 'Madagascar',
    'bulgaria': 'Bulgária',
    'mali': 'Mali',
    'eslovaquia': 'Eslováquia',
    'sudao': 'Sudão',
    'lituania': 'Lituânia',
    'honduras': 'Honduras',
    'barem': 'Barém',
    'georgia': 'Geórgia',
    'paraguai': 'Paraguai',
    'coreia_do_norte': 'Coreia do Norte',
    'chade': 'Chade',
    'islandia': 'Islândia',
    'cazaquistao': 'Cazaquistão',
    'kwait': 'Kuwait',
    'jordania': 'Jordânia',
    'catar': 'Catar',
    'eslovenia': 'Eslovênia',
    'libia': 'Líbia',
    'malawi': 'Malawi',
    'burkina_faso': 'Burkina Faso',
    'myanmar': 'Myanmar',
    'costa_rica': 'Costa Rica',
    'chipre': 'Chipre',
    'panama': 'Panamá',
    'ruanda': 'Ruanda',
    'republica_do_congo': 'República do Congo',
    'albania': 'Albânia',
    'estonia': 'Estônia',
    'oma': 'Omã',
    'eritreia': 'Eritreia',
    'guine': 'Guiné',
    'quirguistao': 'Quirguistão',
    'zimbabwe': 'Zimbabwe',
    'iemen': 'Iêmen',
    'laos': 'Laos',
    'letonia': 'Letônia',
    'guatemala': 'Guatemala',
    'macedonia_do_norte': 'Macedônia do Norte',
    'mongolia': 'Mongólia',
    'guine_bissau': 'Guiné Bissau',
    'niger': 'Níger',
    'luxemburgo': 'Luxemburgo',
    'armenia': 'Armênia',
    'somalia': 'Somália',
    'sri_lanka': 'Sri Lanka',
    'mauritania': 'Mauritânia',
    'andorra': 'Andorra',
    'el_salvador': 'El Salvador',
    'zambia': 'Zâmbia',
    'camboja': 'Camboja',
    'liechtenstein': 'Liechtenstein',
    'gabao': 'Gabão',
    'moldavia': 'Moldávia',
    'libano': 'Líbano',
    'tanzania': 'Tanzânia',
    'monaco': 'Mônaco',
    'haiti': 'Haiti',
    'mocambique': 'Moçambique',
    'tajiquistao': 'Tajiquistão',
    'namibia': 'Namíbia ',
    'serra_leoa': 'Serra Leoa',
    'botswana': 'Botswana',
    'montenegro': 'Montenegro',
    'togo': 'Togo',
    'nepal': 'Nepal',
    'micronesia': 'Micronésia',
    'liberia': 'Libéria',
    'benim': 'Benim',
    'barbados': 'Barbados',
    'nicaragua': 'Nicarágua',
    'fiji': 'Fiji',
    'bahamas': 'Bahamas',
    'malta': 'Malta',
    'mauricio': 'Maurício',
    'sudao_do_sul': 'Sudão do Sul',
    'turcomenistao': 'Turcomenistão',
    'lesoto': 'Lesoto',
    'granada': 'Granada',
    'guiana': 'Guiana',
    'brunei': 'Brunei',
    'dominica': 'Dominica',
    'san_marino': 'San Marino',
    'seicheles': 'Seicheles',
    'gambia': 'Gâmbia',
    'palau': 'Palau',
    'vanuatu': 'Vanuatu',
    'maldivas': 'Maldivas',
    'suriname': 'Suriname',
    'samoa': 'Samoa',
    'djibouti': 'Djibouti',
    'tonga': 'Tonga',
    'vaticano': 'Vaticano',
    'tuvalu': 'Tuvalu',
    'essuatini': 'Essuatíni',
    'comores': 'Comores',
    'nauru': 'Nauru',
    'santa_lucia': 'Santa Lúcia',
    'burundi': 'Burundi',
    'timor_leste': 'Timor Leste',
    'ilhas_salomao': 'Ilhas Salomão',
    'ilhas_marshall': 'Ilhas Marshall',
    'belize': 'Belize',
    'butao': 'Butão',
    'kiribati': 'Kiribati',
    'guine_equatorial': 'Guiné Equatorial',
    'antigua_e_barbuda': 'Antígua e Barbuda',
    'bosnia_e_herzegovina': 'Bósnia e Herzegovina',
    'republica_democratica_do_congo': 'República Democrática do Congo',
    'republica_dominicana': 'República Dominicana',
    'papua_nova_guine': 'Papua Nova Guiné',
    'republica_centro_africana': 'República Centro Africana',
    'cabo_verde': 'Cabo Verde',
    'sao_cristovao_e_neves': 'São Cristóvão e Neves',
    'sao_vicente_e_granadinas': 'São Vicente e Granadinas',
    'trinidad_e_tobago': 'Trinidad e Tobago',
    'costa_do_marfim': 'Costa do Marfim',
    'sao_tome_e_principe': 'São Tomé e Príncipe',
    'emirados_arabes_unidos': 'Emirados Árabes Unidos',
}

def formatar_bandeiras(pasta):
    bandeiras_formatadas = {}

    for arquivo in os.listdir(pasta):
        if arquivo.lower().endswith((".png", ".jpg", ".jpeg")):
            nome_base = os.path.splitext(arquivo)[0].lower()  # Ex: "estados_unidos"
            if nome_base in nomes_certos:
                nome_legivel = nomes_certos[nome_base]
                caminho = os.path.join(pasta, arquivo)
                bandeiras_formatadas[nome_legivel] = caminho
            else:
                print(f"[!] Aviso: nome '{nome_base}' não está no dicionário 'nomes_legiveis'.")

    return bandeiras_formatadas